services:
  base: # this is just here to build the base image for the others to use
    build:
      context: .
      dockerfile: ./util/Server/Dockerfile
    entrypoint: ["true"]
  admin:
    build:
      context: .
      dockerfile: ./src/Admin/Dockerfile
    ports:
      - "62911:5000"
    volumes:
      - ./config/:/config
      - ./logs/:/var/log/bitwarden
    env_file:
      - ./dev/.env
  attachments:
    build:
      context: .
      dockerfile: ./util/Attachments/Dockerfile
    ports:
      - "50004:5000"
    volumes:
      - ./config/:/config
      - ./logs/:/var/log/bitwarden
    environment:
      LOCAL_UID: "${PUID}"
      LOCAL_GID: "${PGID}"
    env_file:
      - ./dev/.env
  api:
    build:
      context: .
      dockerfile: ./src/Api/Dockerfile
    ports:
      - "4000:5000"
    volumes:
      - ./config/:/config
      - ./logs/:/var/log/bitwarden
    env_file:
      - ./dev/.env
  icons:
    build:
      context: .
      dockerfile: ./src/Icons/Dockerfile
    ports:
      - "50024:5000"
    env_file:
      - ./dev/.env
  identity:
    build:
      context: .
      dockerfile: ./src/Identity/Dockerfile
    ports:
      - "33656:5000"
    volumes:
      - ./config/:/config
      - ./logs/:/var/log/bitwarden
      - ./dev:/home/app/config # identity.pfx exists here
    env_file:
      - ./dev/.env
  mssql:
    image: bitwarden/mssql:2025.1.4
    container_name: bitwarden-mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: true
    env_file:
      - ./dev/.env
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   volumes:
  #     - "./dev/reverse-proxy.conf:/etc/nginx/conf.d/default.conf"
  #   ports:
  #     - "${API_PROXY_PORT:-4100}:${API_PROXY_PORT:-4100}"
  #     - "${IDENTITY_PROXY_PORT:-33756}:${IDENTITY_PROXY_PORT:-33756}"

