helm:
  parameters:
  - name: component.admin.image.name
    value: bitwardenprod.azurecr.io/admin
    forcestring: true
  - name: component.admin.image.tag
    value: ephemeral-environment-hello-world@sha256:100180a34fed5990b3ad73837a3234b8c1335f751d66660c35c739254a23345c
    forcestring: true
