general:
  webVersionOverride: 2024.6.0
component:
  admin:
    image:
      name: bitwardenprod.azurecr.io/admin
      tag: ephemeral-environment-hello-world@sha256:e5fb7382640bc0e66b3fc30c790527c30377f253553f67b286a10f520c92e830
  api:
    image:
      name: bitwardenprod.azurecr.io/api
  attachments:
    image:
      name: bitwardenprod.azurecr.io/attachments
  events:
    image:
      name: bitwardenprod.azurecr.io/events
  icons:
    image:
      name: bitwardenprod.azurecr.io/icons
  identity:
    image:
      name: bitwardenprod.azurecr.io/identity
  notifications:
    image:
      name: bitwardenprod.azurecr.io/notifications
  scim:
    image:
      name: bitwardenprod.azurecr.io/scim
  sso:
    image:
      name: bitwardenprod.azurecr.io/sso
  web:
    image:
      name: bitwardenprod.azurecr.io/web
supportComponents:
  dbMigrator:
    image:
      name: bitwardenprod.azurecr.io/mssqlmigratorutility
