helm:
  parameters:
  - name: component.admin.image.name
    value: bitwardenprod.azurecr.io/admin
    forcestring: true
  - name: component.admin.image.tag
    value: ephemeral-environment-hello-world@sha256:f2cdba3c0dc8b94154d3f9911c190981363a25345d4f513d499af2d74c56cd69
    forcestring: true
