services:
  bitwarden_server:
    image: mcr.microsoft.com/devcontainers/dotnet:8.0
    volumes:
      - ../../:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  bitwarden_mail:
    image: sj26/mailcatcher:latest
    restart: unless-stopped
    network_mode: service:bitwarden_server
    
volumes:
  mssql_dev_data:
